# Generated by Django 3.2.18 on 2023-05-07 03:23

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time and date')),
                ('num_hearts', models.IntegerField(choices=[(1, 'Not Bad'), (2, 'Nice'), (3, 'Favorite'), (4, 'Pure Joy'), (5, 'Happiness')], verbose_name='Number of hearts')),
                ('where', models.CharField(choices=[('HOM', '집, Home Sweet Home'), ('CAF', '카페, 커피숍'), ('TEA', '티룸, 찻집'), ('OUT', '야외, 캠핑'), ('ETC', '그 외의 장소')], max_length=3, verbose_name='place')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ManyToManyField(to='recipes.Recipe', verbose_name='recipe chosen')),
            ],
        ),
    ]
