# Generated by Django 3.2.18 on 2023-05-07 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bev_name', models.CharField(max_length=50, verbose_name='beverage name')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_type', models.CharField(choices=[('ROOM', '상온'), ('HOT', '뜨겁게'), ('WARM', '따뜻하게'), ('COOL', '시원하게'), ('ICED', '얼음 넣어서')], default='WARM', max_length=10)),
                ('brew_details', models.TextField(blank=True, verbose_name='Brew details')),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.beverage')),
            ],
        ),
    ]
